#!/bin/bash

seleccioarxiu=$(zenity --file-selection --directory --title="Selecciona directori per les fotos")

for i in $(ls $seleccioarxiu/*.jpg); do
convert $i -resize 150x200! $seleccioarxiu/$(echo $i | rev | cut -d "/" -f1 | rev | cut -d "." -f1)-br.jpeg
done
